apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: cartographer-tap-install-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: cartographer-tap-install-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: cartographer-tap-install-sa
  generation: 1
  name: cartographer
  namespace: tap-install
spec:
  packageRef:
    refName: cartographer.tanzu.vmware.com
    versionSelection:
      constraints: 0.0.6
      prereleases: {}
  serviceAccountName: cartographer-tap-install-sa