apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: cloud-native-runtimes-tap-install-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: cloud-native-runtimes-tap-install-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: cloud-native-runtimes-tap-install-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: cloud-native-runtimes-tap-install-sa
  name: cloud-native-runtimes
  namespace: tap-install
spec:
  packageRef:
    refName: cnrs.tanzu.vmware.com
    versionSelection:
      constraints: 1.0.2
      prereleases: {}
  serviceAccountName: cloud-native-runtimes-tap-install-sa
  values:
  - secretRef:
      name: cloud-native-runtimes-tap-install-values