apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: default-supply-chain-tap-install-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: default-supply-chain-tap-install-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: default-supply-chain-tap-install-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: default-supply-chain-tap-install-sa
  name: default-supply-chain
  namespace: tap-install
spec:
  packageRef:
    refName: default-supply-chain.tanzu.vmware.com
    versionSelection:
      constraints: 0.2.0
      prereleases: {}
  serviceAccountName: default-supply-chain-tap-install-sa
  values:
  - secretRef:
      name: default-supply-chain-tap-install-values