apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: image-policy-webhook-tap-install-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: image-policy-webhook-tap-install-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: image-policy-webhook-tap-install-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: image-policy-webhook-tap-install-sa
  name: image-policy-webhook
  namespace: tap-install
spec:
  packageRef:
    refName: image-policy-webhook.signing.run.tanzu.vmware.com
    versionSelection:
      constraints: 1.0.0-beta.0
      prereleases: {}
  serviceAccountName: image-policy-webhook-tap-install-sa
  values:
  - secretRef:
      name: image-policy-webhook-tap-install-values