apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: scan-controller-tap-install-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: scan-controller-tap-install-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: scan-controller-tap-install-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: scan-controller-tap-install-sa
  name: scan-controller
  namespace: tap-install
spec:
  packageRef:
    refName: scanning.apps.tanzu.vmware.com
    versionSelection:
      constraints: 1.0.0-beta
      prereleases: {}
  serviceAccountName: scan-controller-tap-install-sa
  values:
  - secretRef:
      name: scan-controller-tap-install-values