apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: cloud-native-runtimes-tap-install
  name: cloud-native-runtimes-tap-install-sa
  namespace: tap-install