apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: convention-controller-tap-install
  name: convention-controller-tap-install-sa
  namespace: tap-install