apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: service-bindings-tap-install
  name: service-bindings-tap-install-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-bindings-tap-install-cluster-role
subjects:
- kind: ServiceAccount
  name: service-bindings-tap-install-sa
  namespace: tap-install