apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: app-live-view-tap-install-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: app-live-view-tap-install-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: app-live-view-tap-install-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: app-live-view-tap-install-sa
  generation: 1
  name: app-live-view
  namespace: tap-install
spec:
  packageRef:
    refName: appliveview.tanzu.vmware.com
    versionSelection:
      constraints: 0.2.0
      prereleases: {}
  serviceAccountName: app-live-view-tap-install-sa
  values:
  - secretRef:
      name: app-live-view-tap-install-values