apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: grype-scanner-tap-install-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: grype-scanner-tap-install-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: grype-scanner-tap-install-sa
  name: grype-scanner
  namespace: tap-install
spec:
  packageRef:
    refName: grype.scanning.apps.tanzu.vmware.com
    versionSelection:
      constraints: 1.0.0-beta
      prereleases: {}
  serviceAccountName: grype-scanner-tap-install-sa