apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: service-bindings-tap-install-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: service-bindings-tap-install-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: service-bindings-tap-install-sa
  name: service-bindings
  namespace: tap-install
spec:
  packageRef:
    refName: service-bindings.labs.vmware.com
    versionSelection:
      constraints: 0.5.0
      prereleases: {}
  serviceAccountName: service-bindings-tap-install-sa