apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: source-controller-tap-install-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: source-controller-tap-install-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: source-controller-tap-install-sa
  name: source-controller
  namespace: tap-install
spec:
  packageRef:
    refName: controller.source.apps.tanzu.vmware.com
    versionSelection:
      constraints: 0.1.2
      prereleases: {}
  serviceAccountName: source-controller-tap-install-sa